version: '3'
services:
  psql-server:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: nodeapp
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: VISITORS

#  nginx-server:
#    restart: always
#    build: ./app/
#    ports:
#      - "80:80"
