version: '3'

services:
  psql-server:
#    image: postgres:14.4-alpine
    build: ./postgres/
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}

  node-server:
    depends_on:
      - psql-server
    build: ./node/
    env_file:
      - "./.env"
    ports:
      - "80:8080"

#  nginx-server:  
#    restart: always
#    build: ./app/
#    ports:
#      - "80:80"
